server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: pace

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    encoding:
      charset: UTF-8


jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration-time: 3600000 # 1시간 (밀리초 단위)
  refresh-token:
    expiration-time: 1209600000 # 14일
  temp-token:
    expiration-time: 600000 # 10분
  issuer: pace-server

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  authorization-uri: https://kauth.kakao.com/oauth/authorize
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me

google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY}
